version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.4
    container_name: cirrus-sqs-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development
    volumes:
      - ./meili_data:/data.ms